import "./globals.css";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mobiz Assesment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="">
          <NextAuthProvider>
            <div className="min-h-screen">{children}</div>
          </NextAuthProvider>
        </main>
      </body>
    </html>
  );
}
